/**
 * Created by Administrator on 2017/9/22.
 */
const FormModel = {
  name: '',
  phoneticize: '',
  penName: '',
  authorIntroduction: '',
  sex: '',
  nationality: '',
  age: '',
  birthday: '',
  province: '',
  city: '',
  postalAddress: '',
  identificationCard: '',
  postalCode: '',
  mobilePhone: '',
  fixedPhone: '',
  email: '',
  qq: '',
  fax: '',
  microBlog: '',
  otherContactWay: '',
  school: '',
  majorclass: '',
  url: '',
  teamCnName: '',
  teamEnName: '',
  teamContacter: '',
  teamAddress: '',
  worksCnName: '',
  worksEnName: '',
  worksIntroduction: '',
  country: '',
  award: '',
  broadcasting: '',
  tutor: '',
  finishingDate: '',
  lengthOfWork: '',
  copyrightOwner: '',
  authorSignature: '',
  unit: '',
  unitContacter: '',
  creator: ''
}
export default FormModel
