# Version: 0.0.1
# 使用基础镜像nginx
FROM nginx
# 作者
MAINTAINER HQJ "150091225@qq.com"
# 运行命令
#RUN apt-get update
RUN apt-get install -y tar
# 安装node.js环境,下载源码,解压源码,编译安装
RUN mkdir -p /usr/local/node
COPY node-v8.11.1-linux-x64/ /usr/local/node/
RUN tar -xzf /usr/local/node/node-v8.11.1-linux-x64.tar.gz -C /usr/local/node \
  && ln -s /usr/local/node/node-v8.11.1-linux-x64/bin/node /usr/local/bin/node \
  && ln -s /usr/local/node/node-v8.11.1-linux-x64/bin/npm /usr/local/bin/npm
#RUN npm install -g forever
# 删除nginx 默认配置
RUN rm /etc/nginx/conf.d/default.conf
# 添加我们自己的配置 default.conf 在下面
ADD default.conf /etc/nginx/conf.d/
# 把dist文件夹下的文件copy到nginx下面去
COPY dist/ /usr/share/nginx/html/
RUN mkdir -p /home/app-develop/project/kalix-express-project
COPY kalix-express-project/ /home/app-develop/project/kalix-express-project
#RUN node /home/app-develop/project/kalix-express-project/bin/www
#CMD ["node", "/home/app-develop/project/kalix-express-project/bin/www"]

RUN mkdir -p /var/log/supervisor
COPY supervisord.conf /etc/supervisord.conf

EXPOSE 9000 3000
CMD ["/usr/bin/supervisord"]
